"""
Course: Artificial Intelligence Technology
Institution: FIAP
Project: Cardiology Conversational Assistant
Author: Raphael Silva Lone
Student ID: RM561452

Description:
Service responsible for the integration between the Flask application
and IBM watsonx Assistant. It handles authentication, conversation
session creation, message processing, and extraction of text responses.

This system is intended for educational purposes only and does not
provide medical diagnoses or replace professional medical evaluation.
"""

import os

from dotenv import load_dotenv
from ibm_cloud_sdk_core.authenticators import IAMAuthenticator
from ibm_watson import AssistantV2


# Load environment variables from the local .env file.
# Sensitive credentials must not be stored directly in the source code.
load_dotenv()

API_KEY = os.getenv("WATSON_API_KEY")
SERVICE_URL = os.getenv("WATSON_URL")
ASSISTANT_ID = os.getenv("WATSON_ASSISTANT_ID")
ENVIRONMENT_ID = os.getenv("WATSON_ENVIRONMENT_ID")


# Stop the application if any required Watson credential is missing.
if not all([
    API_KEY,
    SERVICE_URL,
    ASSISTANT_ID,
    ENVIRONMENT_ID
]):
    raise RuntimeError(
        "Watson credentials are missing. Check your .env file."
    )


# Authenticate with IBM Cloud using IAM authentication.
authenticator = IAMAuthenticator(API_KEY)

assistant = AssistantV2(
    version="2024-08-25",
    authenticator=authenticator
)

assistant.set_service_url(SERVICE_URL)


def create_session():
    """
    Create a new conversation session with IBM watsonx Assistant.

    Returns:
        str: Watson session identifier.
    """

    response = assistant.create_session(
        assistant_id=ASSISTANT_ID,
        environment_id=ENVIRONMENT_ID
    ).get_result()

    return response["session_id"]


def send_message(session_id, message, user_id):
    """
    Send a user message to an existing Watson conversation session.

    Args:
        session_id (str): Active Watson session identifier.
        message (str): Message entered by the user.
        user_id (str): Anonymous identifier for the current user.

    Returns:
        str: Text response generated by the assistant.
    """

    response = assistant.message(
        assistant_id=ASSISTANT_ID,
        environment_id=ENVIRONMENT_ID,
        session_id=session_id,

        input={
            "message_type": "text",
            "text": message
        },

        # Watson requires a user identifier for custom API clients.
        # This identifier is anonymous and does not contain personal data.
        user_id=user_id

    ).get_result()

    messages = response.get("output", {}).get("generic", [])

    texts = []

    for item in messages:
        if item.get("response_type") == "text":
            texts.append(item.get("text", ""))

    if not texts:
        return "The assistant did not return a text response."

    return "\n".join(texts)